// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUobBIWqq1AIAL1qOcS3_uk5Q8XOdhOeU',
    appId: '1:1030517976734:web:683643534d102b87d8158f',
    messagingSenderId: '1030517976734',
    projectId: 'medtrack-2fda1',
    authDomain: 'medtrack-2fda1.firebaseapp.com',
    storageBucket: 'medtrack-2fda1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYCaj6l20JJPgIGa8ne-qwKuRjceLMOg',
    appId: '1:1030517976734:android:0772c7b892ed6d82d8158f',
    messagingSenderId: '1030517976734',
    projectId: 'medtrack-2fda1',
    storageBucket: 'medtrack-2fda1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWMnqHcDRM_yE2kio63IzK-ivU39RNto',
    appId: '1:1030517976734:ios:58e55540ed4f610fd8158f',
    messagingSenderId: '1030517976734',
    projectId: 'medtrack-2fda1',
    storageBucket: 'medtrack-2fda1.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWMnqHcDRM_yE2kio63IzK-ivU39RNto',
    appId: '1:1030517976734:ios:58e55540ed4f610fd8158f',
    messagingSenderId: '1030517976734',
    projectId: 'medtrack-2fda1',
    storageBucket: 'medtrack-2fda1.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUobBIWqq1AIAL1qOcS3_uk5Q8XOdhOeU',
    appId: '1:1030517976734:web:d16776ea92968971d8158f',
    messagingSenderId: '1030517976734',
    projectId: 'medtrack-2fda1',
    authDomain: 'medtrack-2fda1.firebaseapp.com',
    storageBucket: 'medtrack-2fda1.firebasestorage.app',
  );
}
